/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUser"];
        put: operations["updateUser"];
        post: operations["createUser"];
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findEmployee"];
        put: operations["updateEmployee"];
        post: operations["createEmployee"];
        delete: operations["deleteEmployee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery-state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findDeliveryState"];
        put: operations["updateDeliveryState"];
        post: operations["createDeliveryState"];
        delete: operations["deleteDeliveryState"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findCourse"];
        put: operations["updateCourse"];
        post: operations["createCourse"];
        delete: operations["deleteCourse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findContract"];
        put: operations["updateContract"];
        post: operations["createContract"];
        delete: operations["deleteContract"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findClient"];
        put: operations["updateClient"];
        post: operations["createClient"];
        delete: operations["deleteClient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPosition"];
        put?: never;
        post: operations["createPosition"];
        delete: operations["deletePosition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createLoad"];
        delete: operations["deleteLoad"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/load/assign-to-course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["assignLoadsToCourse"];
        trace?: never;
    };
    "/user/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/position/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAllPositions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/employee/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findEmployeeList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delivery-state/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findDeliveryStateList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findCourseList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contract/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findContractList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClientList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserSaveRequest: {
            /** Format: int64 */
            id?: number;
            email?: string;
            password?: string;
            roles?: ("NONE" | "DRIVER" | "FORWARDER" | "MANAGER" | "ADMIN")[];
        };
        UserSummaryDTO: {
            /** Format: int64 */
            id?: number;
            email?: string;
            roles?: ("NONE" | "DRIVER" | "FORWARDER" | "MANAGER" | "ADMIN")[];
        };
        EmployeeSaveRequest: {
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
            /** Format: int64 */
            position?: number;
            user?: components["schemas"]["UserSaveRequest"];
        };
        CourseSummaryDTO: {
            /** Format: int64 */
            id?: number;
            destination?: string;
            /** Format: date-time */
            date?: string;
        };
        EmployeeDTO: {
            /** Format: int64 */
            id?: number;
            firstName?: string;
            lastName?: string;
            phoneNumber?: string;
            position?: components["schemas"]["PositionDTO"];
            courses?: components["schemas"]["CourseSummaryDTO"][];
            user?: components["schemas"]["UserSummaryDTO"];
        };
        PositionDTO: {
            /** Format: int64 */
            id?: number;
            position?: string;
        };
        DeliveryStateSaveRequest: {
            location?: string;
            /** @enum {string} */
            deliveryState?: "PENDING" | "ACCEPTED" | "IN_WAREHOUSE" | "ASSIGNED" | "IN_TRANSIT" | "OUT_FOR_DELIVERY" | "DELIVERED" | "FAILED_ATTEMPT" | "RETURNED" | "CANCELLED";
            comment?: string;
        };
        DeliveryStateDTO: {
            /** Format: int64 */
            id?: number;
            location?: string;
            /** @enum {string} */
            deliveryState?: "PENDING" | "ACCEPTED" | "IN_WAREHOUSE" | "ASSIGNED" | "IN_TRANSIT" | "OUT_FOR_DELIVERY" | "DELIVERED" | "FAILED_ATTEMPT" | "RETURNED" | "CANCELLED";
            comment?: string;
            /** Format: date-time */
            lastUpdated?: string;
        };
        CourseSaveRequest: {
            destination?: string;
            /** Format: date-time */
            date?: string;
            description?: string;
            /** Format: double */
            cost?: number;
            /** Format: int64 */
            driver?: number;
        };
        ContractSummaryDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        CourseDTO: {
            /** Format: int64 */
            id?: number;
            destination?: string;
            /** Format: date-time */
            date?: string;
            description?: string;
            /** Format: double */
            cost?: number;
            loads?: components["schemas"]["LoadSummaryDTO"][];
            driver?: components["schemas"]["DriverSummaryDTO"];
        };
        DriverSummaryDTO: {
            /** Format: int64 */
            id?: number;
            firstName?: string;
            lastName?: string;
        };
        LoadSummaryDTO: {
            /** Format: int64 */
            id?: number;
            identifier?: string;
            contract?: components["schemas"]["ContractSummaryDTO"];
        };
        ContractSaveRequest: {
            name?: string;
            senderAddress?: string;
            deliveryAddress?: string;
            /** Format: int64 */
            clientId?: number;
        };
        ClientSummaryDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            nip?: string;
            deliveryAddress?: string;
        };
        ContractDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            senderAddress?: string;
            deliveryAddress?: string;
            client?: components["schemas"]["ClientSummaryDTO"];
        };
        ClientSaveRequest: {
            name?: string;
            nip?: string;
            phoneNumber?: string;
            email?: string;
        };
        ClientDTO: {
            /** Format: int64 */
            id?: number;
            name?: string;
            nip?: string;
            phoneNumber?: string;
            email?: string;
            contracts?: components["schemas"]["ContractSummaryDTO"][];
        };
        LoadSaveRequest: {
            identifier?: string;
            type?: string;
            /** @enum {string} */
            size?: "SMALL" | "MEDIUM" | "LARGE";
            /** Format: float */
            weight?: number;
            /** Format: double */
            worth?: number;
            /** Format: int64 */
            contractId?: number;
            /** Format: int64 */
            deliveryStateId?: number;
        };
        LoadDTO: {
            /** Format: int64 */
            id?: number;
            identifier?: string;
            type?: string;
            /** @enum {string} */
            size?: "SMALL" | "MEDIUM" | "LARGE";
            /** Format: float */
            weight?: number;
            /** Format: double */
            worth?: number;
            contract?: components["schemas"]["ContractSummaryDTO"];
            deliveryState?: components["schemas"]["DeliveryStateDTO"];
            /** Format: int64 */
            courseId?: number;
        };
        UserRegisterRequest: {
            email?: string;
            password?: string;
        };
        JwtResponse: {
            token?: string;
            /** Format: date-time */
            expiration?: string;
        };
        LoginRequest: {
            email?: string;
            password?: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageMetadata: {
            /** Format: int64 */
            size?: number;
            /** Format: int64 */
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int64 */
            totalPages?: number;
        };
        PagedModelUserSummaryDTO: {
            content?: components["schemas"]["UserSummaryDTO"][];
            page?: components["schemas"]["PageMetadata"];
        };
        EmployeeSummaryDTO: {
            /** Format: int64 */
            id?: number;
            firstName?: string;
            lastName?: string;
            position?: string;
        };
        PagedModelEmployeeSummaryDTO: {
            content?: components["schemas"]["EmployeeSummaryDTO"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PagedModelDeliveryStateDTO: {
            content?: components["schemas"]["DeliveryStateDTO"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PagedModelCourseSummaryDTO: {
            content?: components["schemas"]["CourseSummaryDTO"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PagedModelContractSummaryDTO: {
            content?: components["schemas"]["ContractSummaryDTO"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PagedModelClientSummaryDTO: {
            content?: components["schemas"]["ClientSummaryDTO"][];
            page?: components["schemas"]["PageMetadata"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUser: {
        parameters: {
            query: {
                userId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryDTO"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryDTO"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryDTO"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query: {
                userId: number;
            };
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findEmployee: {
        parameters: {
            query: {
                employeeId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeDTO"];
                };
            };
        };
    };
    updateEmployee: {
        parameters: {
            query: {
                employeeId: number;
            };
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeDTO"];
                };
            };
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EmployeeDTO"];
                };
            };
        };
    };
    deleteEmployee: {
        parameters: {
            query: {
                employeeId: number;
            };
            header: {
                Authorization: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findDeliveryState: {
        parameters: {
            query: {
                deliveryStateId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeliveryStateDTO"];
                };
            };
        };
    };
    updateDeliveryState: {
        parameters: {
            query: {
                deliveryStateId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryStateSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeliveryStateDTO"];
                };
            };
        };
    };
    createDeliveryState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeliveryStateSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DeliveryStateDTO"];
                };
            };
        };
    };
    deleteDeliveryState: {
        parameters: {
            query: {
                deliveryStateId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findCourse: {
        parameters: {
            query: {
                courseId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseDTO"];
                };
            };
        };
    };
    updateCourse: {
        parameters: {
            query: {
                courseId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseDTO"];
                };
            };
        };
    };
    createCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CourseDTO"];
                };
            };
        };
    };
    deleteCourse: {
        parameters: {
            query: {
                courseId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findContract: {
        parameters: {
            query: {
                contractId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractDTO"];
                };
            };
        };
    };
    updateContract: {
        parameters: {
            query: {
                contractId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractDTO"];
                };
            };
        };
    };
    createContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContractDTO"];
                };
            };
        };
    };
    deleteContract: {
        parameters: {
            query: {
                contractId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findClient: {
        parameters: {
            query: {
                clientId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientDTO"];
                };
            };
        };
    };
    updateClient: {
        parameters: {
            query: {
                clientId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientDTO"];
                };
            };
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClientDTO"];
                };
            };
        };
    };
    deleteClient: {
        parameters: {
            query: {
                clientId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPosition: {
        parameters: {
            query: {
                positionId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PositionDTO"];
                };
            };
        };
    };
    createPosition: {
        parameters: {
            query: {
                position: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PositionDTO"];
                };
            };
        };
    };
    deletePosition: {
        parameters: {
            query: {
                positionId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createLoad: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoadSaveRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoadDTO"];
                };
            };
        };
    };
    deleteLoad: {
        parameters: {
            query: {
                loadId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryDTO"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                refreshToken: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JwtResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                refreshToken: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JwtResponse"];
                };
            };
        };
    };
    assignLoadsToCourse: {
        parameters: {
            query: {
                courseId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": number[];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findUsers: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelUserSummaryDTO"];
                };
            };
        };
    };
    findAllPositions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PositionDTO"][];
                };
            };
        };
    };
    findEmployeeList: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelEmployeeSummaryDTO"];
                };
            };
        };
    };
    findDeliveryStateList: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelDeliveryStateDTO"];
                };
            };
        };
    };
    findCourseList: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelCourseSummaryDTO"];
                };
            };
        };
    };
    findContractList: {
        parameters: {
            query: {
                clientName?: string;
                city?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelContractSummaryDTO"];
                };
            };
        };
    };
    getClientList: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PagedModelClientSummaryDTO"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryDTO"];
                };
            };
        };
    };
}
